### ISSUE TITLE
License for Project

### ISSUE THREAD

**Issue by beautiful-coffee** [HenryHeffan/PyWhitakersWords#1]
Hi!

As a Latin student who’s used Whitaker’s Words, I’m very impressed by this project! I make a lot of projects that have utilized the Ada version of Whitakers in the past, but maintaining the Ada edition is somewhat difficult given its age, Python support is much better. Thus, I’d like to use this project’s code in future Latin educational programs, would you be willing to release the code in this repository under a specific license to allow that, such as MIT/Apache 2.0/etc?

Thank you!

**Comment by HenryHeffan** [comment]
Sure! I just released it under the GPL license. Hope it turns out to be useful to you!

**Comment by beautiful-coffee** [comment]
Thank you so much!
